-- 코드를 입력하세요
SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rv.REVIEW_SCORE), 2) SCORE
FROM REST_INFO ri
    INNER JOIN REST_REVIEW rv ON ri.REST_ID = rv.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_ID
ORDER BY SCORE DESC, ri.FAVORITES DESC;