SELECT i.REST_ID
     , i.REST_NAME
     , i.FOOD_TYPE
     , i.FAVORITES
     , i.ADDRESS
     , ROUND(AVG(r.REVIEW_SCORE), 2) SCORE
FROM REST_INFO i
    JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC;

















-- 코드를 입력하세요
# SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rv.REVIEW_SCORE), 2) SCORE
# FROM REST_INFO ri
#     INNER JOIN REST_REVIEW rv ON ri.REST_ID = rv.REST_ID
# WHERE ri.ADDRESS LIKE '%서울%'
# GROUP BY ri.REST_ID
# ORDER BY SCORE DESC, ri.FAVORITES DESC;