SELECT YEAR(o.SALES_DATE) YEAR
     , MONTH(o.SALES_DATE) MONTH
     , i.GENDER
     , COUNT(DISTINCT o.USER_ID) USERS
FROM USER_INFO i
    JOIN ONLINE_SALE o ON i.USER_ID = o.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), i.GENDER
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), i.GENDER;