SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
    JOIN ITEM_TREE t ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY i.ITEM_ID DESC;

















-- 코드를 작성해주세요
# SELECT info.ITEM_ID, info.ITEM_NAME, info.RARITY
# FROM ITEM_INFO info
#     INNER JOIN ITEM_TREE tree ON info.ITEM_ID = tree.ITEM_ID
# WHERE tree.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
# ORDER BY ITEM_ID DESC;