SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN ('C#', 'Python')) > 0
ORDER BY ID;














# SELECT DISTINCT(ID), EMAIL, FIRSTNAME, LASTNAME
# FROM DEVELOPERS D, SKILLCODES S
# WHERE (D.SKILL_CODE & S.CODE )>0 AND S.NAME REGEXP 'Python|C#'
# ORDER BY ID;