SELECT h.FLAVOR
FROM FIRST_HALF h
    JOIN ICECREAM_INFO i ON h.FLAVOR = i.FLAVOR
WHERE h.TOTAL_ORDER > 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY h.TOTAL_ORDER DESC;














-- 코드를 입력하세요
# SELECT info.FLAVOR
# FROM ICECREAM_INFO info
#     INNER JOIN FIRST_HALF half ON info.FLAVOR = half.FLAVOR
# WHERE half.TOTAL_ORDER > 3000 AND info.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY half.TOTAL_ORDER DESC;