SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;















-- 코드를 입력하세요
# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') 'PUBLISHED_DATE'
# FROM BOOK
# WHERE PUBLISHED_DATE >= '2021-01-01' AND PUBLISHED_DATE <= '2021-12-31' AND CATEGORY = '인문'
# ORDER BY PUBLISHED_DATE;