SELECT SUM(G.SCORE) SCORE
     , G.EMP_NO
     , E.EMP_NAME
     , POSITION
     , EMAIL
    FROM HR_GRADE G
    LEFT JOIN HR_EMPLOYEES E
        ON G.EMP_NO = E.EMP_NO
    GROUP BY G.EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1;